insert into organizations (id, name, fullname, organizationtype, address) values (1, 'Abatz', 'yandex.ru', 'COMMERCIAL', '73421 Clemons Junction');
insert into organizations (id, name, fullname, organizationtype, address) values (2, 'Jabbersphere', 'amazon.co.jp', 'PUBLIC', '3688 Charing Cross Plaza');
insert into organizations (id, name, fullname, organizationtype, address) values (3, 'Zazio', 'blinklist.com', 'PUBLIC', '4 Milwaukee Center');
insert into organizations (id, name, fullname, organizationtype, address) values (4, 'Divape', 'mozilla.org', 'COMMERCIAL', '436 Northfield Junction');
insert into organizations (id, name, fullname, organizationtype, address) values (5, 'Browsebug', 'myspace.com', 'TRUST', '94949 Bunker Hill Street');
insert into organizations (id, name, fullname, organizationtype, address) values (6, 'Tagchat', 'hubpages.com', 'OPEN_JOINT_STOCK_COMPANY', '4 Rigney Junction');
insert into organizations (id, name, fullname, organizationtype, address) values (7, 'Dabfeed', 'si.edu', 'OPEN_JOINT_STOCK_COMPANY', '9641 Crownhardt Circle');
insert into organizations (id, name, fullname, organizationtype, address) values (8, 'Linkbuzz', 'studiopress.com', 'OPEN_JOINT_STOCK_COMPANY', '2108 Debra Terrace');
insert into organizations (id, name, fullname, organizationtype, address) values (9, 'Fivebridge', 'dagondesign.com', 'TRUST', '18 Fallview Point');
insert into organizations (id, name, fullname, organizationtype, address) values (10, 'Eidel', 'deliciousdays.com', 'OPEN_JOINT_STOCK_COMPANY', '03973 Talmadge Alley');
insert into organizations (id, name, fullname, organizationtype, address) values (11, 'Flashspan', 'networkadvertising.org', 'OPEN_JOINT_STOCK_COMPANY', '629 Morningstar Way');
insert into organizations (id, name, fullname, organizationtype, address) values (12, 'Trupe', 'paypal.com', 'OPEN_JOINT_STOCK_COMPANY', '7 3rd Place');
insert into organizations (id, name, fullname, organizationtype, address) values (13, 'Thoughtworks', 'dropbox.com', 'OPEN_JOINT_STOCK_COMPANY', '2008 North Circle');
insert into organizations (id, name, fullname, organizationtype, address) values (14, 'Gevee', 'wikispaces.com', 'TRUST', '37 Golden Leaf Crossing');
insert into organizations (id, name, fullname, organizationtype, address) values (15, 'Riffpedia', 'google.ca', 'COMMERCIAL', '706 Jana Pass');
insert into organizations (id, name, fullname, organizationtype, address) values (16, 'Realbridge', 'uol.com.br', 'PUBLIC', '5 Cody Drive');
insert into organizations (id, name, fullname, organizationtype, address) values (17, 'Voolia', '163.com', 'COMMERCIAL', '847 Iowa Court');
insert into organizations (id, name, fullname, organizationtype, address) values (18, 'Roombo', 'harvard.edu', 'PUBLIC', '02 Nobel Pass');
insert into organizations (id, name, fullname, organizationtype, address) values (19, 'Youtags', 'fastcompany.com', 'COMMERCIAL', '474 Gina Circle');
insert into organizations (id, name, fullname, organizationtype, address) values (20, 'Feedbug', 'purevolume.com', 'OPEN_JOINT_STOCK_COMPANY', '58120 Crescent Oaks Park');
insert into organizations (id, name, fullname, organizationtype, address) values (21, 'Trudeo', 'themeforest.net', 'TRUST', '26584 Rutledge Junction');
insert into organizations (id, name, fullname, organizationtype, address) values (22, 'Trilith', 'businessinsider.com', 'OPEN_JOINT_STOCK_COMPANY', '3 Stuart Terrace');
insert into organizations (id, name, fullname, organizationtype, address) values (23, 'Divavu', 'dailymotion.com', 'PUBLIC', '4 Pierstorff Avenue');
insert into organizations (id, name, fullname, organizationtype, address) values (24, 'Photobug', 'hc360.com', 'TRUST', '5 Milwaukee Street');
insert into organizations (id, name, fullname, organizationtype, address) values (25, 'Myworks', 'comcast.net', 'COMMERCIAL', '78 High Crossing Pass');
insert into organizations (id, name, fullname, organizationtype, address) values (26, 'Youspan', 'ucoz.ru', 'PUBLIC', '9741 Sunnyside Trail');
insert into organizations (id, name, fullname, organizationtype, address) values (27, 'Voolith', 'uol.com.br', 'PUBLIC', '3705 Bowman Way');
insert into organizations (id, name, fullname, organizationtype, address) values (28, 'Fiveclub', 'vimeo.com', 'TRUST', '9290 Macpherson Place');
insert into organizations (id, name, fullname, organizationtype, address) values (29, 'Jaloo', 'storify.com', 'COMMERCIAL', '86 Summerview Place');
insert into organizations (id, name, fullname, organizationtype, address) values (30, 'Zoonder', 'symantec.com', 'TRUST', '2411 Southridge Plaza');
insert into organizations (id, name, fullname, organizationtype, address) values (31, 'Gabtype', 'wufoo.com', 'COMMERCIAL', '4 High Crossing Center');
insert into organizations (id, name, fullname, organizationtype, address) values (32, 'Jetpulse', 'usda.gov', 'OPEN_JOINT_STOCK_COMPANY', '920 Ilene Plaza');
insert into organizations (id, name, fullname, organizationtype, address) values (33, 'Skinder', 'bloglovin.com', 'OPEN_JOINT_STOCK_COMPANY', '4 Lindbergh Pass');
insert into organizations (id, name, fullname, organizationtype, address) values (34, 'Skiptube', 'cocolog-nifty.com', 'TRUST', '689 Grayhawk Circle');
insert into organizations (id, name, fullname, organizationtype, address) values (35, 'Linkbuzz', 'epa.gov', 'COMMERCIAL', '15 Eliot Alley');
insert into organizations (id, name, fullname, organizationtype, address) values (36, 'Oozz', 'theguardian.com', 'OPEN_JOINT_STOCK_COMPANY', '89 Straubel Lane');
insert into organizations (id, name, fullname, organizationtype, address) values (37, 'Bluejam', 'imgur.com', 'OPEN_JOINT_STOCK_COMPANY', '136 Forest Dale Pass');
insert into organizations (id, name, fullname, organizationtype, address) values (38, 'Skiba', 'cyberchimps.com', 'PUBLIC', '90 Kennedy Circle');
insert into organizations (id, name, fullname, organizationtype, address) values (39, 'Voolia', 'ucoz.ru', 'OPEN_JOINT_STOCK_COMPANY', '9257 Brentwood Center');
insert into organizations (id, name, fullname, organizationtype, address) values (40, 'Devpoint', 'prlog.org', 'TRUST', '67 Morningstar Terrace');
insert into organizations (id, name, fullname, organizationtype, address) values (41, 'Twimbo', 'pagesperso-orange.fr', 'COMMERCIAL', '8880 Redwing Trail');
insert into organizations (id, name, fullname, organizationtype, address) values (42, 'Camimbo', 'youtu.be', 'OPEN_JOINT_STOCK_COMPANY', '12 Linden Drive');
insert into organizations (id, name, fullname, organizationtype, address) values (43, 'Jabbercube', 't.co', 'PUBLIC', '34877 Wayridge Center');
insert into organizations (id, name, fullname, organizationtype, address) values (44, 'Podcat', 'loc.gov', 'COMMERCIAL', '760 Jay Road');
insert into organizations (id, name, fullname, organizationtype, address) values (45, 'Skyble', 'columbia.edu', 'PUBLIC', '6497 Del Mar Pass');
insert into organizations (id, name, fullname, organizationtype, address) values (46, 'Lazzy', 'mail.ru', 'PUBLIC', '32182 Heffernan Park');
insert into organizations (id, name, fullname, organizationtype, address) values (47, 'Realmix', 'aol.com', 'PUBLIC', '71 Transport Avenue');
insert into organizations (id, name, fullname, organizationtype, address) values (48, 'Trilia', 'dropbox.com', 'PUBLIC', '2165 Randy Way');
insert into organizations (id, name, fullname, organizationtype, address) values (49, 'Thoughtstorm', 'answers.com', 'TRUST', '3668 Packers Trail');
insert into organizations (id, name, fullname, organizationtype, address) values (50, 'Ozu', 'npr.org', 'PUBLIC', '739 Mccormick Terrace');
insert into organizations (id, name, fullname, organizationtype, address) values (51, 'Aivee', 'nymag.com', 'TRUST', '5771 Bunker Hill Road');
insert into organizations (id, name, fullname, organizationtype, address) values (52, 'Quinu', 'jimdo.com', 'TRUST', '5417 Haas Street');
insert into organizations (id, name, fullname, organizationtype, address) values (53, 'Plajo', 'umn.edu', 'TRUST', '3660 Pankratz Way');
insert into organizations (id, name, fullname, organizationtype, address) values (54, 'Thoughtworks', 'icq.com', 'TRUST', '52 Golf View Street');
insert into organizations (id, name, fullname, organizationtype, address) values (55, 'Oloo', 'netvibes.com', 'TRUST', '28 Clyde Gallagher Pass');
insert into organizations (id, name, fullname, organizationtype, address) values (56, 'Jaxbean', 'dmoz.org', 'OPEN_JOINT_STOCK_COMPANY', '9 Mosinee Way');
insert into organizations (id, name, fullname, organizationtype, address) values (57, 'Roombo', 'freewebs.com', 'OPEN_JOINT_STOCK_COMPANY', '12 Leroy Trail');
insert into organizations (id, name, fullname, organizationtype, address) values (58, 'Youspan', 'patch.com', 'COMMERCIAL', '08156 Lawn Street');
insert into organizations (id, name, fullname, organizationtype, address) values (59, 'Oloo', 'ucoz.com', 'COMMERCIAL', '737 Everett Circle');
insert into organizations (id, name, fullname, organizationtype, address) values (60, 'Devify', 'berkeley.edu', 'PUBLIC', '0 Parkside Court');
insert into organizations (id, name, fullname, organizationtype, address) values (61, 'Riffwire', 'jigsy.com', 'TRUST', '405 Boyd Park');
insert into organizations (id, name, fullname, organizationtype, address) values (62, 'Rhyloo', 'example.com', 'PUBLIC', '8 New Castle Pass');
insert into organizations (id, name, fullname, organizationtype, address) values (63, 'Trunyx', 'census.gov', 'OPEN_JOINT_STOCK_COMPANY', '66823 Paget Alley');
insert into organizations (id, name, fullname, organizationtype, address) values (64, 'Linkbuzz', 'de.vu', 'TRUST', '8373 Sugar Lane');
insert into organizations (id, name, fullname, organizationtype, address) values (65, 'Realcube', 'delicious.com', 'PUBLIC', '6 Merrick Alley');
insert into organizations (id, name, fullname, organizationtype, address) values (66, 'Ozu', 'google.nl', 'TRUST', '861 Rowland Pass');
insert into organizations (id, name, fullname, organizationtype, address) values (67, 'Divape', 'sphinn.com', 'COMMERCIAL', '4 Fuller Place');
insert into organizations (id, name, fullname, organizationtype, address) values (68, 'Wordpedia', 'japanpost.jp', 'OPEN_JOINT_STOCK_COMPANY', '8 Mendota Point');
insert into organizations (id, name, fullname, organizationtype, address) values (69, 'Quire', 'mapquest.com', 'OPEN_JOINT_STOCK_COMPANY', '36550 Spaight Junction');
insert into organizations (id, name, fullname, organizationtype, address) values (70, 'Meezzy', 'wufoo.com', 'OPEN_JOINT_STOCK_COMPANY', '82 Macpherson Way');
insert into organizations (id, name, fullname, organizationtype, address) values (71, 'Skinte', 'omniture.com', 'TRUST', '88 Vera Terrace');
insert into organizations (id, name, fullname, organizationtype, address) values (72, 'Topicware', 'wunderground.com', 'TRUST', '509 1st Street');
insert into organizations (id, name, fullname, organizationtype, address) values (73, 'Voomm', 'bravesites.com', 'PUBLIC', '8 Ilene Way');
insert into organizations (id, name, fullname, organizationtype, address) values (74, 'Devpoint', 'about.com', 'TRUST', '453 Thackeray Alley');
insert into organizations (id, name, fullname, organizationtype, address) values (75, 'Zoomlounge', 'blogtalkradio.com', 'OPEN_JOINT_STOCK_COMPANY', '51 Grover Pass');
insert into organizations (id, name, fullname, organizationtype, address) values (76, 'Youbridge', 'flavors.me', 'COMMERCIAL', '80837 Toban Avenue');
insert into organizations (id, name, fullname, organizationtype, address) values (77, 'Realfire', 'networkadvertising.org', 'OPEN_JOINT_STOCK_COMPANY', '0493 International Avenue');
insert into organizations (id, name, fullname, organizationtype, address) values (78, 'Gigaclub', 'typepad.com', 'COMMERCIAL', '9 Ohio Plaza');
insert into organizations (id, name, fullname, organizationtype, address) values (79, 'Meezzy', 'zdnet.com', 'PUBLIC', '35 Dahle Drive');
insert into organizations (id, name, fullname, organizationtype, address) values (80, 'Oodoo', 'hatena.ne.jp', 'TRUST', '5 Toban Drive');
insert into organizations (id, name, fullname, organizationtype, address) values (81, 'Skalith', 'amazon.com', 'OPEN_JOINT_STOCK_COMPANY', '667 Drewry Crossing');
insert into organizations (id, name, fullname, organizationtype, address) values (82, 'Mita', 'w3.org', 'PUBLIC', '18573 Eagle Crest Pass');
insert into organizations (id, name, fullname, organizationtype, address) values (83, 'Quaxo', 'newyorker.com', 'OPEN_JOINT_STOCK_COMPANY', '4611 Bartelt Road');
insert into organizations (id, name, fullname, organizationtype, address) values (84, 'Skyble', 'blinklist.com', 'OPEN_JOINT_STOCK_COMPANY', '28941 Golf Course Point');
insert into organizations (id, name, fullname, organizationtype, address) values (85, 'Edgetag', 'dyndns.org', 'PUBLIC', '90 Duke Point');
insert into organizations (id, name, fullname, organizationtype, address) values (86, 'Centidel', 'cyberchimps.com', 'PUBLIC', '474 Drewry Avenue');
insert into organizations (id, name, fullname, organizationtype, address) values (87, 'Jamia', 'furl.net', 'COMMERCIAL', '416 2nd Street');
insert into organizations (id, name, fullname, organizationtype, address) values (88, 'Viva', 'timesonline.co.uk', 'OPEN_JOINT_STOCK_COMPANY', '7774 Sherman Hill');
insert into organizations (id, name, fullname, organizationtype, address) values (89, 'Blogtags', 't-online.de', 'PUBLIC', '41 Hoffman Road');
insert into organizations (id, name, fullname, organizationtype, address) values (90, 'Skinix', 'printfriendly.com', 'TRUST', '55 Birchwood Alley');
insert into organizations (id, name, fullname, organizationtype, address) values (91, 'Quinu', 'unesco.org', 'OPEN_JOINT_STOCK_COMPANY', '80835 Hovde Place');
insert into organizations (id, name, fullname, organizationtype, address) values (92, 'Browsetype', 'tumblr.com', 'OPEN_JOINT_STOCK_COMPANY', '55 Colorado Street');
insert into organizations (id, name, fullname, organizationtype, address) values (93, 'Rhynoodle', 'mediafire.com', 'PUBLIC', '6 Morning Circle');
insert into organizations (id, name, fullname, organizationtype, address) values (94, 'Twitterbeat', 'jalbum.net', 'OPEN_JOINT_STOCK_COMPANY', '67647 Farmco Pass');
insert into organizations (id, name, fullname, organizationtype, address) values (95, 'Agivu', 'narod.ru', 'COMMERCIAL', '539 Park Meadow Place');
insert into organizations (id, name, fullname, organizationtype, address) values (96, 'Wikibox', 'dmoz.org', 'OPEN_JOINT_STOCK_COMPANY', '6057 Waywood Pass');
insert into organizations (id, name, fullname, organizationtype, address) values (97, 'Fivebridge', 'vkontakte.ru', 'COMMERCIAL', '536 Myrtle Center');
insert into organizations (id, name, fullname, organizationtype, address) values (98, 'Topiczoom', 'phpbb.com', 'PUBLIC', '18 Packers Alley');
insert into organizations (id, name, fullname, organizationtype, address) values (99, 'Gabcube', 'wikimedia.org', 'COMMERCIAL', '4 Welch Lane');
insert into organizations (id, name, fullname, organizationtype, address) values (100, 'Jaxbean', 'issuu.com', 'PUBLIC', '6 Farmco Avenue');

